name: subeya
description: "A new Flutter project."

version: 1.0.4+1

environment:
  # Alineado con Dart 3.9 (Flutter 3.35.x)
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  injectable: ^2.5.1
  get_it: ^8.2.0
  fluttertoast: ^8.2.10
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  google_places_flutter: ^2.1.0
  geocoding: ^4.0.0
  # Para dibujar rutas en el mapa
  flutter_polyline_points: ^3.1.0

  # socket 
  socket_io_client: ^3.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints compatibles con Dart 3.9
  flutter_lints: ^5.0.0
  injectable_generator: ^2.8.1
  build_runner: ^2.7.1

  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  flutter_gherkin: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/
